services:
    postgres:
        image: postgres
        container_name: postgres
        hostname: postgres
        ports:
            - 5432:5432
        volumes:
            - progresDB:/data/postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: TEST_DB
        restart: unless-stopped
    api:
        build:
            context: ./
        environment:
            NODE_ENV: dev
        ports:
            - 4000:4000
        depends_on:
            - postgres
        volumes:
            - .:/app
        restart: always
volumes:
    progresDB:
